//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZodiacGlass.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0")]
        public global::System.Windows.Point OverlayPosition {
            get {
                return ((global::System.Windows.Point)(this["OverlayPosition"]));
            }
            set {
                this["OverlayPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::ZodiacGlass.FFXIV.FFXIVMemoryMap MemoryMap {
            get {
                return ((global::ZodiacGlass.FFXIV.FFXIVMemoryMap)(this["MemoryMap"]));
            }
            set {
                this["MemoryMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int OverlayDisplayMode {
            get {
                return ((int)(this["OverlayDisplayMode"]));
            }
            set {
                this["OverlayDisplayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OverlayPinned {
            get {
                return ((bool)(this["OverlayPinned"]));
            }
            set {
                this["OverlayPinned"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WarnedAboutOverlayPinningNotWorkingWithCurrentRuntimeVersion {
            get {
                return ((bool)(this["WarnedAboutOverlayPinningNotWorkingWithCurrentRuntimeVersion"]));
            }
            set {
                this["WarnedAboutOverlayPinningNotWorkingWithCurrentRuntimeVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWarningIfGameModeIsNotSupported {
            get {
                return ((bool)(this["ShowWarningIfGameModeIsNotSupported"]));
            }
            set {
                this["ShowWarningIfGameModeIsNotSupported"] = value;
            }
        }
    }
}
